import React from 'react';
import '../packages/theme/src/css/global.css';

// Apply dark theme styles to body and html
if (typeof document !== 'undefined') {
  document.body.setAttribute('data-theme', 'cnc');
  document.body.style.backgroundColor = 'hsl(240, 10%, 3.9%)';
  document.body.style.color = 'hsl(0, 0%, 98%)';
  document.documentElement.style.backgroundColor = 'hsl(240, 10%, 3.9%)';
  
  // Add custom styles for Storybook UI elements
  const style = document.createElement('style');
  style.textContent = `
    /* Fix Storybook documentation headline colors */
    .sbdocs-wrapper h1,
    .sbdocs-wrapper h2,
    .sbdocs-wrapper h3,
    .sbdocs-wrapper h4,
    .sbdocs-wrapper h5,
    .sbdocs-wrapper h6 {
      color: hsl(0, 0%, 98%) !important;
      background: linear-gradient(135deg, hsl(262, 83%, 58%) 0%, hsl(262, 83%, 75%) 50%, hsl(220, 83%, 65%) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      text-shadow: 0 0 30px hsl(262, 83%, 58% / 0.3);
    }
    
    /* Fix Storybook sidebar and controls text */
    .sidebar-item,
    .sidebar-item[data-selected="true"],
    .sidebar-item[data-selected="false"] {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix story title in Canvas */
    .sb-show-main h1,
    .sb-show-main h2,
    .sb-show-main h3 {
      color: hsl(0, 0%, 98%) !important;
      background: linear-gradient(135deg, hsl(262, 83%, 58%) 0%, hsl(262, 83%, 75%) 50%, hsl(220, 83%, 65%) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
    
    /* Fix controls panel text */
    .docblock-argstable-head th,
    .docblock-argstable-body td {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix description and documentation text */
    .sbdocs-p,
    .sbdocs-li,
    .docblock-description,
    .sbdocs-content p,
    .sbdocs-content div,
    .sbdocs-content span,
    .docblock-markdown > p,
    .docs-story p,
    .docs-story-description {
      color: hsl(240, 5%, 84%) !important;
    }
    
    /* Fix story headers and titles in docs */
    .docs-story h1,
    .docs-story h2,
    .docs-story h3,
    .docs-story h4,
    .sb-story h1,
    .sb-story h2,
    .sb-story h3,
    .sb-story h4,
    .sbdocs-title,
    .sbdocs-subtitle {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix dark text in various Storybook elements */
    .docblock-code-toggle,
    .docblock-source,
    .docblock-canvas,
    .sb-bar,
    .addon-controls-header,
    .addon-controls-body,
    .addon-controls-label {
      color: hsl(240, 5%, 84%) !important;
    }
    
    /* Fix story description in the canvas view */
    [data-docs-id] .docblock-description,
    .sb-wrapper .docblock-description,
    .sb-show-main .docblock-description {
      color: hsl(240, 5%, 84%) !important;
    }
    
    /* Additional Storybook v8 text color fixes */
    .sb-story,
    .sb-main-padded,
    .sb-main-centered,
    .sb-main-fullscreen,
    .sb-main-nopadding {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix all Storybook text content */
    .sb-show-main,
    .sb-show-main *,
    [data-story-id],
    [data-story-id] *,
    .sbdocs-wrapper,
    .sbdocs-wrapper * {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Specifically fix story titles and labels */
    .sb-story__name,
    .sb-story-title,
    .story-name,
    .story-title,
    .sbdocs-h1,
    .sbdocs-h2,
    .sbdocs-h3,
    .sbdocs-h4,
    .sbdocs-h5,
    .sbdocs-h6 {
      color: hsl(0, 0%, 98%) !important;
      background: linear-gradient(135deg, hsl(262, 83%, 58%) 0%, hsl(262, 83%, 75%) 50%, hsl(220, 83%, 65%) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }
    
    /* Fix Canvas toolbar and story labels */
    .sb-bar .sb-bar-item,
    .sb-toolbar .sb-toolbar-item,
    .docs-story-container,
    .docs-story-container *,
    .sb-story-container,
    .sb-story-container * {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Override any remaining gray text */
    [style*="color: rgb(68, 68, 68)"],
    [style*="color: #444"],
    [style*="color: gray"],
    [style*="color: grey"] {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix specific Storybook UI text colors */
    .css-1wa3eu0-placeholder,
    .css-1uccc91-singleValue,
    .css-1rhbuit-multiValue,
    .css-12jo7m5,
    .css-b62m3t-container,
    .css-t3ipsp-control {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Fix section headers in Storybook sidebar and docs */
    .sidebar-header,
    .sidebar-subheading,
    .css-1tqh4d1,
    .css-1qvjx8c,
    .css-1t6k0dh,
    .css-1f8dmx6,
    .css-1aekf7z,
    .css-1dbjc4n,
    .css-1rynq56,
    .css-1t6k0dh-subheading,
    .sidebar-subheading,
    .sidebar-section-header,
    .sidebar-section-title,
    .css-1q8wgtu,
    .css-1b1cj5u,
    .css-1nw2bf8,
    .css-1dbjc4n .css-1rynq56,
    .css-1dbjc4n > div,
    .css-1dbjc4n > span,
    .css-1dbjc4n > p,
    .css-1dbjc4n > h1,
    .css-1dbjc4n > h2,
    .css-1dbjc4n > h3,
    .css-1dbjc4n > h4,
    .css-1dbjc4n > h5,
    .css-1dbjc4n > h6,
    .css-1dbjc4n [data-testid="tree-node-group"],
    .css-1dbjc4n [data-testid="tree-node-group"] *,
    .css-1dbjc4n [data-testid="tree-node-header"],
    .css-1dbjc4n [data-testid="tree-node-header"] *,
    .css-1dbjc4n [data-testid="tree-node-group-header"],
    .css-1dbjc4n [data-testid="tree-node-group-header"] *,
    .css-1dbjc4n [data-testid="tree-node-item"],
    .css-1dbjc4n [data-testid="tree-node-item"] *,
    .css-1dbjc4n [data-testid="tree-node-story"],
    .css-1dbjc4n [data-testid="tree-node-story"] *,
    .css-1dbjc4n [data-testid="tree-node-component"],
    .css-1dbjc4n [data-testid="tree-node-component"] *,
    .css-1dbjc4n [data-testid="tree-node-section"],
    .css-1dbjc4n [data-testid="tree-node-section"] *,
    .css-1dbjc4n [data-testid="tree-node-folder"],
    .css-1dbjc4n [data-testid="tree-node-folder"] *,
    .css-1dbjc4n [data-testid="tree-node-branch"],
    .css-1dbjc4n [data-testid="tree-node-branch"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf"],
    .css-1dbjc4n [data-testid="tree-node-leaf"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-expanded"],
    .css-1dbjc4n [data-testid="tree-node-leaf-expanded"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-collapsed"],
    .css-1dbjc4n [data-testid="tree-node-leaf-collapsed"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-story"],
    .css-1dbjc4n [data-testid="tree-node-leaf-story"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-docs"],
    .css-1dbjc4n [data-testid="tree-node-leaf-docs"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-component"],
    .css-1dbjc4n [data-testid="tree-node-leaf-component"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-section"],
    .css-1dbjc4n [data-testid="tree-node-leaf-section"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-folder"],
    .css-1dbjc4n [data-testid="tree-node-leaf-folder"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-expanded"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-expanded"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-collapsed"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-story"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-story"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-docs"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-docs"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-component"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-component"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-section"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-section"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-folder"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-folder"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-expanded"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-expanded"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-collapsed"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-story"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-story"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-docs"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-docs"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-component"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-component"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-section"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-section"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-folder"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-folder"] *,
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-branch"],
    .css-1dbjc4n [data-testid="tree-node-leaf-branch-branch-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node"],
    .css-1dbjc4n [data-testid="sidebar-tree-node"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-group"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-group"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-group-header"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-group-header"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-item"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-item"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-collapsed"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-docs"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-docs"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-docs"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-docs"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-docs"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-docs"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-docs"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-docs"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-collapsed"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-story"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-story"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-docs"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-docs"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-component"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-component"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-section"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-section"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-folder"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-folder"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch-expanded"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch-expanded"] *,
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch-collapsed"],
    .css-1dbjc4n [data-testid="sidebar-tree-node-leaf-branch-branch-branch-branch-branch-collapsed"] *,
    [data-testid="sidebar-item"],
    [data-testid="sidebar-item"] *,
    [data-testid="sidebar-section"],
    [data-testid="sidebar-section"] *,
    [data-testid="sidebar-section-header"],
    [data-testid="sidebar-section-header"] *,
    [data-testid="sidebar-section-title"],
    [data-testid="sidebar-section-title"] *,
    [data-testid="sidebar-section-subheading"],
    [data-testid="sidebar-section-subheading"] *,
    [data-testid="sidebar-section-link"],
    [data-testid="sidebar-section-link"] *,
    [data-testid="sidebar-section-button"],
    [data-testid="sidebar-section-button"] *,
    [data-testid="sidebar-section-text"],
    [data-testid="sidebar-section-text"] *,
    [data-testid="sidebar-section-label"],
    [data-testid="sidebar-section-label"] *,
    [data-testid="sidebar-section-description"],
    [data-testid="sidebar-section-description"] *,
    [data-testid="sidebar-section-icon"],
    [data-testid="sidebar-section-icon"] *,
    [data-testid="sidebar-section-arrow"],
    [data-testid="sidebar-section-arrow"] *,
    [data-testid="sidebar-section-chevron"],
    [data-testid="sidebar-section-chevron"] *,
    [data-testid="sidebar-section-disclosure"],
    [data-testid="sidebar-section-disclosure"] *,
    [data-testid="sidebar-section-disclosure-header"],
    [data-testid="sidebar-section-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-title"],
    [data-testid="sidebar-section-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-link"],
    [data-testid="sidebar-section-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-button"],
    [data-testid="sidebar-section-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-text"],
    [data-testid="sidebar-section-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-label"],
    [data-testid="sidebar-section-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-description"],
    [data-testid="sidebar-section-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-header"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-title"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-subheading"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-link"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-button"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-text"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-label"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-description"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-icon"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-arrow"] *,
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"],
    [data-testid="sidebar-section-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-disclosure-chevron"] * {
      color: hsl(0, 0%, 98%) !important;
    }
    
    /* Catch-all for Storybook sidebar navigation */
    .sidebar-container *,
    .sidebar-container div,
    .sidebar-container span,
    .sidebar-container p,
    .sidebar-container h1,
    .sidebar-container h2,
    .sidebar-container h3,
    .sidebar-container h4,
    .sidebar-container h5,
    .sidebar-container h6,
    .sidebar-container button,
    .sidebar-container a,
    .sidebar-container li,
    .sidebar-container label,
    .sidebar-container summary,
    .sidebar-container details,
    .sidebar-container ul,
    .sidebar-container ol,
    .sidebar-container nav,
    .sidebar-container section,
    .sidebar-container article,
    .sidebar-container header,
    .sidebar-container footer,
    .sidebar-container main,
    .sidebar-container aside {
      color: hsl(0, 0%, 98%) !important;
    }
  `;
  document.head.appendChild(style);
}

/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    layout: 'centered',
    backgrounds: {
      default: 'app-dark',
      values: [
        {
          name: 'light',
          value: 'hsl(0, 0%, 100%)',
        },
        {
          name: 'app-dark',
          value: 'hsl(240, 10%, 3.9%)', // Original app background
        },
        {
          name: 'darker',
          value: 'hsl(240, 10%, 2%)', // Even darker variant
        },
        {
          name: 'cnc-industrial',
          value: 'hsl(210, 20%, 8%)', // Industrial blue-tinted dark
        },
      ],
    },
  },
  decorators: [
    (Story) => (
      <div 
        style={{ 
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          padding: '1.5rem',
          backgroundColor: 'hsl(240, 10%, 3.9%)', // --color-background from original
          color: 'hsl(0, 0%, 98%)', // --color-foreground from original
          fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
          overflow: 'auto',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}
      >
        <div style={{ width: '100%', maxWidth: '1200px' }}>
          <Story />
        </div>
      </div>
    ),
  ],
};

export default preview;